package_name := `python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['name'])"`

# Run the CLI without installing
run *args:
    uv run c7-mcp {{ args }}

lint:
    ruff check
    uv run -- pyright .
    uv run -- basedpyright .

format:
    ruff check --fix
    ruff format

test:
    uv run pytest -v .



# Install the CLI tool globally
install:
    uv tool install . --force

# Uninstall the CLI tool
uninstall:
    uv tool uninstall {{ package_name }}

# Reinstall the CLI tool
reinstall:
    uv tool install . --force --reinstall
